import os

MARATHON_INTERVAL_REFRESH_APP=os.getenv("MARATHON_INTERVAL_REFRESH_APP",60)

LABEL_FOR_AUTOSCALE_ENABLE = 'AUTOSCALE_ENABLE'
LABEL_FOR_AUTOSCALE_RMQ_QUEUE = 'AUTOSCALE_RMQ_QUEUE'
LABEL_FOR_AUTOSCALE_RMQ_VHOST = 'AUTOSCALE_RMQ_VHOST'
LABEL_FOR_AUTOSCALE_RMQ_MAX_MESSAGES_QUEUE = 'AUTOSCALE_RMQ_MAX_MESSAGES_QUEUE'
LABEL_FOR_AUTOSCALE_RMQ_MAX_INSTANCES = 'AUTOSCALE_RMQ_MAX_INSTANCES'
LABEL_FOR_AUTOSCALE_RMQ_MIN_INSTANCES = 'AUTOSCALE_RMQ_MIN_INSTANCES'
LABEL_FOR_AUTOSCALE_RMQ_INCREMENT_INSTANCES = 'AUTOSCALE_RMQ_INCREMENT_INSTANCES'
LABEL_FOR_AUTOSCALE_RMQ_DECREMENT_INSTANCES = 'AUTOSCALE_RMQ_DECREMENT_INSTANCES'

MANDATORY_LABELS_APP = [LABEL_FOR_AUTOSCALE_ENABLE,
                        LABEL_FOR_AUTOSCALE_RMQ_QUEUE,
                        LABEL_FOR_AUTOSCALE_RMQ_MAX_MESSAGES_QUEUE,
                        LABEL_FOR_AUTOSCALE_RMQ_MAX_INSTANCES]

OPTIONAL_LABELS_APP = [LABEL_FOR_AUTOSCALE_RMQ_VHOST,
                       LABEL_FOR_AUTOSCALE_RMQ_MIN_INSTANCES,
                       LABEL_FOR_AUTOSCALE_RMQ_INCREMENT_INSTANCES,
                       LABEL_FOR_AUTOSCALE_RMQ_DECREMENT_INSTANCES]